INSERT INTO bobs_burgers (burger_pun)
VALUES  
    ("“New Bacon-ings” – Comes with Bacon"), 
    ("The Child Molester – Comes with Candy!"),
    ("Foot Feta-ish Burger"),
    ("Never Been Feta Burger"),
    ("Tunami – Comes with Tuna"),
    ("Mission A-Corn-Plished Burger – Comes with Corn Salsa"),
    ("Pepper Don’t Preach Burger –  Comes with Pepper"),
    ("Rest in Peas Burger – comes with snap Peas and Carrots"),
    ("Fig-eta Bout It Burger – Comes with Fig"),
    ("Chevre Which Way But Loose Burger – Comes with Chevre Cheese"),
    ("The Roquefort Files Burger –  Comes with Roquefort Cheese"),
    ("These Collards Don’t Run Burger – Comes with Collard Greens"),
    ("Totally Radish Burger – Comes with Radishes"),
    ("Onion Burger Grilled To Death – Comes with Onions"),
    ("Last of the Mo-Jicama Burger – Comes with the Jicama vegetable"),
    ("Olive And Let Die Burger – Comes with Olives"),
    ("Thank God It’s Fried Egg Burger – Comes with a Fried Egg"),
    ("Camembert-ly Legal Burger – Comes with Camembert Cheese"),
    ("Krauted House Burger – Comes with Sauerkraut"),
    ("Poblano Picasso Burger – Comes with Poblano Pepper"),
    ("Salvador Cauliflower Burger – Comes with Cauliflower"),
    ("Shoot out at the Okra Coral Burger Burger – Comes with Okra"),
    ("Give Me Your Best Shallot Burger – Comes with Shallot"),
    ("The Sound & The Curry Burger – Comes with Curry"),
    ("I’ve Created a Muenster Burger – Comes with Muenster cheese"),
    ("Something’s NOT Fishy Burger – With a 100% Beef"),
    ("One Fish, Two Fish, Red Fish Hamburger"),
    ("Take Me Out To The Burger – Comes with Peanuts and Crackerjacks"),
    ("I’m Mad About Saffron – Doesn’t come with Saffron"),
    ("Chard To A Crisp Burger – Comes with the Chard vegetable"),
    ("Burger A La Mode - Comes with ice cream, not on top"),
    ("Shake Your Honeymaker  Burger – Comes with Honey Mustard"),
    ("Use It Or Bleus It Burger – Comes with Blue Cheese"),
    ("The One Yam Band Burger – Comes with Yams"),
    ("Do Brussel Burger – Comes with Brussel Sprouts"),
    ("Papaya Was A Rolling Stone Burger – Comes with Papaya fruit"),
    ("Good Night and Good Leek Burger – Comes with Leek"),
    ("Band On The Bun Burger – Comes with Wings"),
    ("Chorizo Your Own Adventure Burger – Comes with Chorizo sausages"),
    ("It’s fun to eat at the rYe M.C.A Burger – Comes on rye with mustard, cheese and avocado"),
    ("If Looks Could Kale Burger – Comes with the Kale vegetable"),
    ("Little Swiss Bunshine Burger – Comes on a buttered bun"),
    ("The Final Kraut Down Burger – Comes with Sauerkraut"),
    ("“Girls Just Wanna Have Fennel” – Comes with fennel"),
    ("Sit and Spinach Burger – Comes with spinach"),
    ("Sweaty Palms Burger – Comes with hearts of palm"),
    ("Poutine  – on the Ritz Burger – Comes with poutine fries"),
    ("Mesclun Around Burger – Comes with mesclun salad"),
    ("The Don’t Get Creme Fraiche With Me Burger – Comes with Creme Fraiche"),
    ("Onion-tended Consequences Burger"),
    ("Bruschetta Bout It Burger"),
    ("MediterrAin't Misbehavin' Burger"),
    ("I'm Gonna Get You Succotash Burger"),
    ("Every Breath You Tikka Masala Burger"),
    ("Two Karat Burger - Comes with two carrots"),
    ("Say It Ain't Cilantro Burger - Doesn't come with cilantro. Because cilantro is terrible"),
    ("Not If I Can Kelp It Burger"),
    ("The Jack-O-Lentil Burger"),
    ("Itsy Bitsy Teeny Weenie Yellow Polka-Dot Zucchini Burger"),
    ("Summer Thyme Burger"),
    ("Butterface Burger - Served with butter lettuce"),
    ("Beets Me Burger"),
    ("We're Here We're Gruyere, Get Used to It Burger"),
    ("Plymouth Roquefort Burger"),
    ("She's a Super Leek Burger - Comes with braised leeks"),
    ("Let's Get Frisée Burger"),
    ("Open Sesame Burger - Served open-faced on a sesame seed bun"),
    ("Chipotle Off the Old Block Burger"),
    ("Don't Give Me No Chive Burger - Served with no chives"),
    ("Pickle My Funny Bone Burger"),
    ("Yes I Cayenne Burger"),
    ("Bean Spirit - Comes with beans"),
    ("One Horse Open Slaw Burger - Comes with slaw, no horse"),
    ("Santa Claus Is Cumin to Town Burger - With cumin"),
    ("Fifth Day of Christmas Burger - Comes with five golden rings of onion"),
    ("Jingle Bell Pepper Burger"),
    ("Home for the Challah-Days Burger - Comes on a challah roll"),
    ("The Silentil Night Burger - Comes with lentils"),
    ("50 Ways to Leave Your Guava Burger"),
    ("Ruta-Bag-A Burger"),
    ("Don't Go Brocking My Heart Burger - With broccoli and artichoke hearts"),
    ("Eggers Can't Be Cheesers Burger - With fried egg and cheese"),
    ("Freedom of Choys Burger - Comes with bok choy"),
    ("Grandpa Muenster Burger - 10% Senior Discount"),
    ("Mushroom With A View Burger - Porcini on a double decker"),
    ("I Heartichoke You Burger"),
    ("Don't You Four Cheddar 'Bout Me Burger - Comes with four kinds of cheddar"),
    ("I Mint to Do That Burger - Comes with mint relish"),
    ("Only the Provolonely Burger - Comes with provolone"),
    ("Sharp Cheddar Dressed Man - Comes with sharp cheddar"),
    ("I Know Why the Cajun Burger Sings"),
    ("Tarragon in Sixty Seconds Burger"),
    ("Chile Relleno-You-Didn't Burger"),
    ("Top Bun Burger - Comes on our best seven-grain bun"),
    ("Top Butt Burger - Your face looks like a butt"),
    ("So Many Fennel So Little Thyme Burger - Comes with lots of fennel, no thyme"),
    ("National Pass-Thyme Burger"),
    ("Free To Brie You and Me Burger"),
    ("Woulda Coulda Gouda Burger"),
    ("You Gouda Be Kidding Me Burger"),
    ("As Gouda As It Gets Burger"),
    ("Gouda Gouda Gumdrops"),
    ("A Few Gouda Men Burger"),
    ("Gouda Day Sir"),
    ("Gouda Gouda Two Shoes - It comes with shoes"),
    ("The Cauliflower's Cumin from Inside the House Burger - Comes with cauliflower and cumin"),
    ("Sprouts! Sprouts! Sprouts It All Out! Burger"),
    ("A Leek of Their Own Burger"),
    ("Gourdon-Hamsey Burger - Comes with squash and ham"),
    ("I'm OK, You're Ok-ra Burger"),
    ("Bohemian Radishy Burger"),
    ("Edward James Olive-most Burger"),
    ("Is This Your Chard Burger"),
    ("Caper Magic To Yourself Burger - Comes with capers (Also, Magic doesn't exist)"),
    ("I Don't Bay Leaf in Magic Burger"),
    ("Winter Muensterland Burger with Muenster cheese - Side of snow peas"),
    ("The Longest Chard Burger"),
    ("Kale Mary Burger - Served with kale"),
    ("The Troy Oinkman Burger - Served with bacon"),
    ("It's Only Sourdough Burger (But I Like It)"),
    ("Enoki Dokie Burger - Comes with enoki mushrooms"),
    ("I Fought the Slaw Burger (And the Slaw Won)"),
    ("Charbroil Fair Burger - Comes with Parlsey, Sage, Rosemary and Thyme"),
    ("Beets of the Southern Wild Burger"),
    ("Sympathy for the Deviled Egg Burger"),
    ("The Life of the Parsley Burger"),
    ("Sweet Home Avocado Burger"),
    ("To Err Is Cumin Burger"),
    ("Onion Ring Around the Rosemary Burger"),
    ("Sgt. Poblano Pepper's Lonely Artichoke Hearts Club Burger"),
    ("Parma Parma Parma Chameleon Burger - with Parmesan crisp"),
    ("Bleu by You Burger - with locally sourced bleu cheese"),
    ("The Saffron Saff-off Burger"),
    ("Texas Chainsaw Massa-curd Burger"),
    ("The Human Polenta-pede Burger"),
    ("Kales From the Crypt Burger"),
    ("Paranormal Pepper Jack-tivity Burger"),
    ("Sub-conscious Burger - On a sub roll"),
    ("Romaines of the Day Burger"),
    ("Parsnips-Vous Francais Burger"),
    ("Beet-er Late Than Never Burger"),
    ("Peas and Thank You Burger"),
    ("Run Gorgonzola Run Burger - Made with Gorgonzola"),
    ("Cheeses is Born Burger - Comes with baby swiss"),
    ("Cajun Gracefully Burger"),
    ("Blondes Have More Fun-gus Burger - Comes with mushrooms"),
    ("Beets of Burden Burger - Served with too many beets"),
    ("Blue is the Warmest Cheese Burger"),
    ("Three Beets to the Wind Burger"),
    ("The Grand Brie Burger"),
    ("A Good Manchego is Hard to Find Burger"),
    ("The Garden of Eden Burger - Served with Apple"),
    ("Shoestring Around the Rosey Burger"),
    ("Let it Snow Peas Burger"),
    ("Knife to Beet You Burger - w/Thinly Sliced Beets"),
    ("I Ran So Taro Way Burger"),
    ("Curd-fect Strangers Burger - Comes with cheese curds"),
    ("Sweet Chili O' Mine Burger"),
    ("The Six Scallion Dollar Man Burger"),
    ("Let's Give 'em Something Shiitake 'bout Burger"),
    ("If You've Got It, Croissant It Burger"),
    ("Chile Relleno-You-Didn't Burger"),
    ("Parm-pit Burger - Comes with Parmesan"),
    ("Scent of a Cumin Burger"),
    ("She'll be Coming 'round the Plantain Burger"),
    ("Take A Leek Burger – Comes with sautéed leeks"),
    ("Who Wants To Be A Scallionaire Burger?"),
    ("The Yam Ship Burger - Comes with yams"),
    ("You can't fight City Challa Burger - Comes on a Challah roll"),
    ("Snipwrecked Burger - Comes with parsnips"),
    ("Breaking Radish Burger - Comes with a slice of Radish"),
    ("The Pear Tree Burger  - With sliced pears (partridge not included)"),
    ("Cole came, cole slaw, cole conquered Burger"),
    ("Be My Valen-thyme Burger"),
    ("The Say Cheese Burger"),
    ("It Takes Bun to Know Bun Burger - Comes on a fancy bun"),
    ("Heads Shoulders Knees and Tomatoes Burger"),
    ("'m Picklish Burger - Comes with pickles"),
    ("Runny Out of Thyme Burger - Comes with a runny fried egg"),
    ("Total Eclipse of the Havarti Burger"),
    ("Ring Around the Collard Burger"),
    ("To Thine Own Self be Bleu Burger - Served with bleu cheese"),
    ("Edamame Dearest Burger - Comes with edamame"),
    ("Barley Davidson Burger - Comes on a barley roll"),
    ("Captain Pepper Jack Marrow Burger"),
    ("Curry On My Wayward Bun Burger"),
    ("Frisee It, Don’t Spray It Burger"),
    ("We Bought a Zucchini Burger"),
    ("All In A Glaze Work Burger - Served with Balsamic Glaze"),
    ("If At First You Sesame Seed, Thai, Thai, Again Burger"),
    ("Turn the Other Leek Burger"),
    ("Fig Lebowski Burger"),
    ("My Farro Lady Burger"),
    ("hutney the Front Door Burger - Comes with Mango Chutney"),
    ("You're Kimchi the Best Burger"),
    ("Teriyaki a New One Burger"),
    ("Aw Nuts Burger - Comes with peanut butter"),
    ("The Glass Fromagerie Burger"),
    ("The Hand That Rocks the Bagel Burger - Comes with an everything bagel"),
    ("Put Me in Poached Burger - Comes with a poached egg"),
    ("Endive Had the Time of My Life Burger"),
    ("You Spinach Me Right Round Spinach Burger"),
    ("Wasabi My Guest Burger"),
    ("Muenster Under the Bun Burger"),
    ("Do Fry for Me Argentina Burger"),
    ("I Know What You Did Last Summer Squash Burger"),
    ("I Know What You Did Last Summer Squash Burger"),
    ("Corned Identity Burger - Comes with corned beef"),
    ("Tangled Up in Blueberry Burger - Comes with a blueberry compote"),
    ("When Harry Met Salumi Burger"),
    ("The Olives Kitteridge Burger - with olive tapenade"),
    ("Jagged Little Dill Burger"),
    ("Away in a Mango Burger"),
    ("Caper the Friendly Goat Cheese Burger - Served with capers & feta"),
    ("Video Killed the Radicchio Star Burger"),
    ("Andrew Diced Carrots Burger - Comes with pickled diced carrots"),
    ("Garlic Shandling Burger"),
    ("Little Red Bruschett-a Burger"),
    ("Walking in a Winter Comes-with-cran Burger - Comes with cranberry sauce"),
    ("Stilton on the Dock of the Bun Burger"),
    ("It's My Havarti and I'll Rye If I Want To"),
    ("Fingerling Brothers and Barnum and Bay Leaves Burger"),
    ("Citizen Kale Burger"),
    ("It Takes Two to Mango Burger"),
    ("Nothing Compares 2 Blue (Cheese) Burger"),
    ("For Those About to Roquefort We Salute You Burger"),
    ("The Oh Con-Pear Burger"),
    ("Emergency Eggs-it Burger"),
    ("Passion of the Cress Burger"),
    ("Creminis and Misdemeanies Burger - Comes with cremini mushrooms"),
    ("Glory, Glory, Jalapeño! Burger"),
    ("Riding in Cars with Bok Choys Burger"),
    ("Pear Goes the Neighborhood - Comes with a side of pear salad"),
    ("The Blanc Canvas Burger - Comes with a fromage blanc"),
    ("Topless the Morning To You Burger"),
    ("Weekend at Bearnaise Burger"),
    ("The Clear and Present Ginger Burger"),
    ("The Catch Me If You Cran Burger - Served with cranberry sauce"),
    ("The Ebeneezer Bleu-ge Burger"),
    ("Twas the Nut Before Christmas Burger - Comes with walnut aioli"),
    ("The Shut Up and Swiss Me Burger"),
    ("Step Into the Okra-tagon Burger"),
    ("Havarti Like It's 1999 Burger"),
    ("Smells Like Bean Spirit Burger"),
    ("Corn This Way Burger"),
    ("The Sous-vide and the Banshees Burger"),
    ("The Full Head of Heir-loom Tomato Burger"),
    ("The What's Kala-mata with You Burger"),
    ("The Olive What She's Having Burger"),
    ("The Rosemary's Baby Spinach Burger"),
    ("The Wasabi with You Burger"),
    ("The Heirloom Where it Happens Burger"),
    ("Judy Garlic Burger"),
    ("You Won't Believe It's Not Buttersquash Burger - Served with zucchini"),
    ("The Paprika Smurf Burger - Comes with blue potato fries"),
    ("The Here I Am Broccoli Like a Hurricane Burger"),
    ("The Older with More Eggs-perience Burger - Aged burger with a fried egg on top"),
    ("Portobello the Belt Burger"),
    ("Walk This Waioli Burger - Comes with wasabi aioli"),
    ("Shishito Corleone Burger - Comes with shishito peppers"),
    ("The Gouda Wife Burger - Comes with Mature Gouda"),
    ("The Sun'll Come Out To-Marrow Burger - Comes with bone marrow"),
    ("The Sneakin' Celery Down the Alley Burger"),
    ("The 500 Glaze of Summer Burger - Comes with Pomegranate Glaze"),
    ("The I'm Getting Too Old For This Shishito Burger"),
    ("The Don't Dream It's Okra Burger"),
    ("The Stop or My Mom Will Shoots Burger - Comes with pea shoots"),
    ("The Dragonfruit me to Hell Burger"),
    ("Won't Baguette Fooled Again Burger"),
    ("Tumeric-a the Beautiful Burger"),
    ("The Finders Capers Burger"),
    ("The Cops and Rabe-ers Burger - Topped with broccoli rabes"),
    ("Little Chop of Horseradish Burger"),
    ("My Bloody Kale-entine Burger"),
    ("The Absentee Shallot Burger - Comes with crispy shallots"),
    ("The Land of the Slaw-st Burger - Comes with pickle slaw"),
    ("Focaccia Red Handed Burger - On focaccia with beets"),
    ("The Frankie Goes to Hollandaise Burger"),
    ("The Fifty Glaze to Eat Your Burger"),
    ("The Throw Your Hands in the Heirloom Burger"),
    ("The Colby by Your Name Burger"),
    ("Around the World in Eighty Dates Burger"),
    ("The Figgy Smalls Burger"),
    ("Dill Crazy After All These Gruyeres Burger"),
    ("Smilla's Sense of Snowpeas Burger"),
    ("The Santa Slaws is Coming to Town Burger"),
    ("The Brussel and Flow Burger - Served with Brussel sprouts"),
    ("The Mush-aroom About Nothing Burger"),
    ("Sealed with a Swiss Burger"),
    ("Two Left Beet Burger"),
    ("I Love You Just the Whey You Are Burger"),
    ("I Hate to See You Brie-ve But I Love to Watch You Go Burger"),
    ("Murder, Kimchi Wrote Burger"),
    ("The Chevre Little Thing She Does is Magic Burger"),
    ("The Gorgon-Baby-Gone Burger - Comes with gorgonzola cheese"),
    ("The Straight and Marrow Burger - Comes with marrow"),
    ("All Hot and Collard Burger"),
    ("Someone Raclette the Bed Burger - Comes with raclette cheese"),
    ("Ruth Tomater Ginsburger - Comes with heirloom tomatoes and pickled ginger"),
    ("The Devil's Avocado-cate Burger"),
    ("Fleetwood Jack Burger - Comes with sweet little pies, jack cheese"),
    ("The Judge Brine-Hold Burger"),
    ("One Flew Okra the Couscous Nest Burger"),
    ("Lordy Lordy Look Who's RoqueFort-y Burger"),
    ("Hickory Chicory Guac Burger"),
    ("Pea-Brie's Big Adventure Burger - Pea protein burger w/ brie"),
    ("The Olive Me Why Not Take Olive Me? Burger"),
    ("The Hunt for Red Onion-tober Burger - On focaccia with beets"),
    ("What If Peapod Was One of Us Burger"), 
    ("28 Maize Later Burger - Comes with corn salsa"),
    ("The Corn-juring Two Burger - Comes with even more corn salsa"),
    ("The Thousand Chard Stare Burger - Comes with thousand island dressing and swiss chard"),
    ("Hawk and Chickpeas Burger"),
    ("Twisted Swiss-ster Burger"),
    ("The Oaxaca Waka Waka Burger - Comes with Oaxaca cheese"),
    ("The Creme Fraiche Prince of Bell Peppers Burger"),
    ("The Fried off into the Sunset Burger - Comes with a fried egg"),
    ("The Ber-Gouda Triangle Burger"),
    ("The Mama Said There'd Be Glaze Like This Burger - Comes with a Worcestershire glaze"),
    ("The Easy Come, Asiago Burger"),
    ("The Random Jacks of Chive-ness Burger - With Monterrey Jack cheese and chives"),
    ("If It's Yellow Let it Portobello Burger - With yellow peppers and portobello mushroom"),
    ("The Thin Red Pepper Burger"),
    ("The Goat Tell It on the Mountain Burger - Comes with goat cheese"),
    ("The Glazed and Infused Burger - Bourbon glazed and infused with bacon"),
    ("The 'Shroom Where It Happens Burger"),
    ("Cloves Encounters Burger"),
    ("In Ricotta Da Vida Burger"),
    ("Nice Guys Spinach Last Burger"),
    ("This Is What It Sounds Like When Cloves Fry Burger - With fried garlic cloves"),
    ("The Happy Paint Patty's Day Burger - Whiskey brushed patty"),
    ("The Hollandaise RO-O-OH-O-OH-O-OH-OH-OH-OLL Burger - Comes with hollandaise sauce on a Kaiser roll"),
    ("Better Cauliflower Saul Burger"),
    ("The Chili-delphia Story Burger"),
    ("The Deep Blue Brie Burger - Comes with blue cheese and brie"),
    ("The Stayin' A-chive Burger"),
    ("The Almond Butters Band Burger - Comes with toasted almond butter"),
    ("Avoca-don't You Wante Me Baby? Burger"),
    ("Take A Picture Fig'll Last Longer Burger"),
    ("Bet It All on Black Garlic Burger");

    





























































